# dev config
mysql:
  host: localhost
  port: 13306
  user: root
  password: 123456
  db_name: snowball

mysql_unix:
  host: snowball_mysql
  port: 3306
  user: root
  password: snowball_mysql
  db_name: snowball

tushare:
  tokenid: bf83c5640925af523fa3b291697e94eaf216c062fc83087399e95249
